name: Build release packages

on:
  push:
    tags:
      - '*'

jobs:
  linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Install libraries
        run: sudo apt-get install -y libxkbcommon-x11-dev mesa-common-dev freeglut3 freeglut3-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev

      - name: Download Qt 6.5.3 Compiler for Ubuntu 20.04
        working-directory: ${{ runner.temp }}
        run: |
            wget https://github.com/Bolbe/Tools/raw/refs/heads/main/precompiled/ubuntu/Qt653-ubuntu2004.tar.xz
            tar xf ./Qt653-ubuntu2004.tar.xz

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Compile project and build package
        env:
          QT_PATH: ${{ runner.temp }}/Qt-6.5.3
        working-directory: ${{ github.workspace }}
        run: bash ./build-linux.sh

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: grootcam-linux
          path: ${{ github.workspace }}/grootcam.AppImage

  windows:
    runs-on: windows-2019

    steps:
      - name: Download MinGW 11.2.0
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z
          target: ${{ runner.temp }}\

      - name: Unzip MinGW 11.2.0 to mingw64
        working-directory: ${{ runner.temp }}
        run: 7z x x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z

      - name: Download Qt MinGW64
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: https://github.com/Bolbe/Tools/raw/refs/heads/main/precompiled/windows/QtMingw64.7z
          target: ${{ runner.temp }}\

      - name: Unzip Qt MinGW64 to QtMingw64
        working-directory: ${{ runner.temp }}
        run: 7z x QtMingw64.7z

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build project
        working-directory: ${{ github.workspace }}
        env:
           Qt_path: ${{ runner.temp }}/QtMingw64
           Mingw_path: ${{ runner.temp }}/mingw64
        run: pwsh ./build-windows.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: grootcam-windows
          path: ${{ github.workspace }}\grootcamcontrol.zip

  mac:
    runs-on: macos-latest

    steps:
      - name: Download Qt 6.5.3 Compiler for MacOS
        working-directory: ${{ runner.temp }}
        run: |
            wget https://github.com/Bolbe/Tools/raw/refs/heads/main/precompiled/macos/Qt653-macos.tar.xz
            tar xf ./Qt653-macos.tar.xz

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Compile project and build package
        env:
          QT_PATH: ${{ runner.temp }}/Qt-6.5.3
        working-directory: ${{ github.workspace }}
        run: zsh ./build-macos.sh

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: grootcam-macos
          path: ${{ github.workspace }}/GrootcamControl.app.zip


