name: Build release packages

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Which build to run'
        required: true
        default: 'linux'
        type: choice
        options:
          - linux-static
          - macos-static-x86_64
          - macos-static-arm64
          - linux
          - macos
          - windows

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  linux-static:
    if: ${{ inputs.target == 'linux-static' }}
    uses: Bolbe/github-build-tools/.github/workflows/qt-build-static-linux.yml@main
    with:
      app_name: GrootcamControl

  linux:
    if: ${{ inputs.target == 'linux' }}
    uses: Bolbe/github-build-tools/.github/workflows/qt-build-linux.yml@main
    with:
      app_name: GrootcamControl
      artifact_name: grootcamcontrol

  windows:
    if: ${{ inputs.target == 'windows' }}
    uses: Bolbe/github-build-tools/.github/workflows/qt-build-windows.yml@main
    with:
      exe_name: GrootcamControl.exe
      artifact_name: grootcamcontrol

  macos:
    if: ${{ inputs.target == 'macos'  }}
    uses: Bolbe/github-build-tools/.github/workflows/qt-build-macos.yml@main
    with:
      app_name: GrootcamControl

  macos-static-x86_64:
    if: ${{ inputs.target == 'macos-static-x86_64' }}
    uses: Bolbe/github-build-tools/.github/workflows/build-app-static-macos.yml@main
    with:
      app_name: GrootcamControl
      chipset: x86_64

  macos-static-arm64:
    if: ${{ inputs.target == 'macos-static-arm64' }}
    uses: Bolbe/github-build-tools/.github/workflows/build-app-static-macos.yml@main
    with:
      app_name: GrootcamControl
      chipset: arm64